name: Draft Release
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-develop.yml # located in .github/ in default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
